// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjK87wj3jUvXDIS9jE93zbPi5WYK5HdAs',
    appId: '1:8064365082:web:1a2b6504d16e83851a57a3',
    messagingSenderId: '8064365082',
    projectId: 'adoptante-bloom',
    authDomain: 'adoptante-bloom.firebaseapp.com',
    storageBucket: 'adoptante-bloom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLG9Es1MUN3rMCHAepB3RylR19p-rcIk',
    appId: '1:8064365082:android:d98b89d5fb4ee4451a57a3',
    messagingSenderId: '8064365082',
    projectId: 'adoptante-bloom',
    storageBucket: 'adoptante-bloom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOYMAv3v4ycbQRuFqI8o3VvfrQSEXxCk',
    appId: '1:8064365082:ios:9c7916c566fec3e41a57a3',
    messagingSenderId: '8064365082',
    projectId: 'adoptante-bloom',
    storageBucket: 'adoptante-bloom.appspot.com',
    iosClientId:
        '8064365082-rjjkmbqpupgait2on5bjskbuph3juu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOYMAv3v4ycbQRuFqI8o3VvfrQSEXxCk',
    appId: '1:8064365082:ios:9c7916c566fec3e41a57a3',
    messagingSenderId: '8064365082',
    projectId: 'adoptante-bloom',
    storageBucket: 'adoptante-bloom.appspot.com',
    iosClientId:
        '8064365082-rjjkmbqpupgait2on5bjskbuph3juu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloom',
  );
}
